services:
    # AbstractSlot or AbstractContentSlot
    ezplatform.http_cache.signalslot.abstract:
        abstract: true
        arguments: ["@ezplatform.http_cache.purge_client", '@ezplatform.http_cache.tag_provider']

    ezplatform.http_cache.signalslot.abstract_publish:
        abstract: true
        arguments: ["@ezplatform.http_cache.purge_client", "@ezplatform.http_cache.tag_provider", "@ezpublish.spi.persistence.cache.locationHandler"]

    # Content
    ezplatform.http_cache.signalslot.copy_content:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\CopyContentSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\CopyContentSignal }

    ezplatform.http_cache.signalslot.copy_subtree:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\CopySubtreeSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\CopySubtreeSignal }

    ezplatform.http_cache.signalslot.create_content_draft:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\CreateContentDraftSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\CreateContentDraftSignal }

    ezplatform.http_cache.signalslot.create_location:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\CreateLocationSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\CreateLocationSignal }

    ezplatform.http_cache.signalslot.delete_content:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\DeleteContentSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\DeleteContentSignal }

    ezplatform.http_cache.signalslot.delete_location:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\DeleteLocationSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\DeleteLocationSignal }

    ezplatform.http_cache.signalslot.delete_version:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\DeleteVersionSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\DeleteVersionSignal }

    ezplatform.http_cache.signalslot.hide_location:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\HideLocationSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\HideLocationSignal }

    ezplatform.http_cache.signalslot.move_subtree:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\MoveSubtreeSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\MoveSubtreeSignal }

    ezplatform.http_cache.signalslot.publish_version:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\PublishVersionSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\PublishVersionSignal }

    ezplatform.http_cache.signalslot.set_content_state:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\SetContentStateSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags:
            - { name: ezpublish.api.slot, signal: ObjectStateService\SetContentStateSignal }

    ezplatform.http_cache.signalslot.swap_location:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\SwapLocationSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\SwapLocationSignal }

    ezplatform.http_cache.signalslot.unhide_location:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\UnhideLocationSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\UnhideLocationSignal }

    ezplatform.http_cache.signalslot.update_content_metadata:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\UpdateContentMetadataSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\UpdateContentMetadataSignal }

    ezplatform.http_cache.signalslot.update_content:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\UpdateContentSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\UpdateContentSignal }

    ezplatform.http_cache.signalslot.update_location:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\UpdateLocationSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: LocationService\UpdateLocationSignal }

    ezplatform.http_cache.signalslot.create_user:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\CreateUserSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags:
            - { name: ezpublish.api.slot, signal: UserService\CreateUserSignal }

    ezplatform.http_cache.signalslot.update_user:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\UpdateUserSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags:
            - { name: ezpublish.api.slot, signal: UserService\UpdateUserSignal }

    ezplatform.http_cache.signalslot.create_user_group:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\CreateUserGroupSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags:
            - { name: ezpublish.api.slot, signal: UserService\CreateUserGroupSignal }

    ezplatform.http_cache.signalslot.update_user_group:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\UpdateUserGroupSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags:
            - { name: ezpublish.api.slot, signal: UserService\UpdateUserGroupSignal }

    ezplatform.http_cache.signalslot.assign_user_to_user_group:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\AssignUserToUserGroupSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: UserService\AssignUserToUserGroupSignal }

    ezplatform.http_cache.signalslot.unassign_user_from_user_group:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\UnassignUserFromUserGroupSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: UserService\UnAssignUserFromUserGroupSignal }

    ezplatform.http_cache.signalslot.trash:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\TrashSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: TrashService\TrashSignal }

    ezplatform.http_cache.signalslot.recover:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\RecoverSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: TrashService\RecoverSignal }

    ezplatform.http_cache.signalslot.remove_translation:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\RemoveTranslationSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\RemoveTranslationSignal }

    ezplatform.http_cache.signalslot.update_url:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\UpdateUrlSlot
        parent: ezplatform.http_cache.signalslot.abstract
        arguments:
            - "@ezpublish.spi.persistence.cache.urlHandler"
        tags:
            - { name: ezpublish.api.slot, signal: URLService\UpdateUrlSignal }

    ezplatform.http_cache.signalslot.hide_content:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\HideContentSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\HideContentSignal }

    ezplatform.http_cache.signalslot.reveal_content:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\RevealContentSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags:
            - { name: ezpublish.api.slot, signal: ContentService\RevealContentSignal }

    # Content Type
    ezplatform.http_cache.signalslot.assign_content_type_group:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\ContentTypeService\AssignContentTypeGroupSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: ContentTypeService\AssignContentTypeGroupSignal }]

    ezplatform.http_cache.signalslot.delete_content_type_group:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\ContentTypeService\DeleteContentTypeGroupSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: ContentTypeService\DeleteContentTypeGroupSignal }]

    ezplatform.http_cache.signalslot.delete_content_type:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\ContentTypeService\DeleteContentTypeSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: ContentTypeService\DeleteContentTypeSignal }]

    ezplatform.http_cache.signalslot.publish_content_type:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\ContentTypeService\PublishContentTypeSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: ContentTypeService\PublishContentTypeDraftSignal }]

    ezplatform.http_cache.signalslot.unassign_content_type_group:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\ContentTypeService\UnassignContentTypeGroupSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: ContentTypeService\UnassignContentTypeGroupSignal }]

    ezplatform.http_cache.signalslot.update_content_type_group:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\ContentTypeService\UpdateContentTypeGroupSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: ContentTypeService\UpdateContentTypeGroupSignal }]

    # Role
    ezplatform.http_cache.signalslot.assign_role:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\RoleService\AssignRoleSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: RoleService\AssignRoleToUserGroupSignal }
            - { name: ezpublish.api.slot, signal: RoleService\AssignRoleToUserSignal }

    ezplatform.http_cache.signalslot.delete_role:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\RoleService\DeleteRoleSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: RoleService\DeleteRoleSignal }]

    ezplatform.http_cache.signalslot.publish_role:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\RoleService\PublishRoleDraftSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: RoleService\PublishRoleDraftSignal }]

    ezplatform.http_cache.signalslot.remove_role_assignment:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\RoleService\RemoveRoleAssignmentSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: RoleService\RemoveRoleAssignmentSignal }]

    ezplatform.http_cache.signalslot.unassign_role:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\RoleService\UnassignRoleSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags:
            - { name: ezpublish.api.slot, signal: RoleService\UnassignRoleFromUserGroupSignal }
            - { name: ezpublish.api.slot, signal: RoleService\UnassignRoleFromUserSignal }

    # Section
    ezplatform.http_cache.signalslot.assign_section:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\SectionService\AssignSectionSlot
        parent: ezplatform.http_cache.signalslot.abstract_publish
        tags: [{ name: ezpublish.api.slot, signal: SectionService\AssignSectionSignal }]

    ezplatform.http_cache.signalslot.delete_section:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\SectionService\DeleteSectionSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: SectionService\DeleteSectionSignal }]

    ezplatform.http_cache.signalslot.update_section:
        class: EzSystems\PlatformHttpCacheBundle\SignalSlot\SectionService\UpdateSectionSlot
        parent: ezplatform.http_cache.signalslot.abstract
        tags: [{ name: ezpublish.api.slot, signal: SectionService\UpdateSectionSignal }]
